service: project4

provider:
  name: aws
  runtime: nodejs8.10
  region: europe-central-1

functions:
  calculate:
    handler: handler.calculate
    events:
      - http:
          path: square-number
          method: get
